<base target="_top"/>

# Disclaimer

Last updated: January 01, 2018

The information contained on https://cenuno.github.io/ website (the "Service")
is for general information purposes only.

Urban Data Science assumes no responsibility for errors or omissions in the
contents on the Service.

In no event shall Urban Data Science be liable for any special, direct,
indirect, consequential, or incidental damages or any damages whatsoever,
whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service.
Urban Data Science reserves the right to make additions, deletions, or
modification to the contents on the Service at any time without prior notice.

Urban Data Science does not warrant that the website is free of viruses or
other harmful components.


## External links disclaimer

https://cenuno.github.io/ website may contain links to external websites that are not provided or maintained by or in any way affiliated with Urban Data Science.

Please note that the Urban Data Science does not guarantee the accuracy,
relevance, timeliness, or completeness of any information on these external
websites.

## Human Error

There will be times I state incorrect recommendations or suggestions. I encourage readers to file a new issue on the [`Issues`](https://github.com/cenuno/cenuno.github.io/issues) tab on the GitHub page for this website. 
